max_epochs: 50
min_epochs: 10

loss:
  type: cross_entropy
  gamma: 2.0
  class_weights: null
  smoothing: 0.1

profiling:
  enabled: true
  steps: 5

optimizer:
  name: adam
  lr: 0.001
  weight_decay: 0.0001
  betas: [0.9, 0.999]

scheduler:
  name: cosine
  T_max: ${train.max_epochs}
  eta_min: 0.00001

early_stopping:
  enabled: false
  monitor: val_loss
  patience: 10
  mode: min

checkpoint:
  monitor: val_acc
  mode: max
  save_top_k: 3
  save_last: true

gradient_clip_val: 0
accumulate_grad_batches: 1

accelerator: auto
devices: 1
precision: 32
